[about]
name = "DEV"
shortname = "devto"
homepage = "https://dev.to"

[profile]
display = "@{claim_uri_1}"
uri = "https://dev.to/{claim_uri_1}"

[claim]
uri = '^https://dev.to/(.*)/(.*)/?'
uri_is_ambiguous = false

[proof]

[proof.request]
uri = "https://dev.to/api/articles/{claim_uri_1}/{claim_uri_2}"
protocol = "http"
access_restrictions = "none"

[proof.response]
format = "json"

[proof.target]
format = "uri"
relation = "contains"
path = ["body_markdown"]