[about]
name = "DEV"
shortname = "devto"
homepage = "https://dev.to"

[profile]
display = "@{{ claim_uri.parts.0 }}"
uri = "https://dev.to/{{ claim_uri.parts.0 }}"

[claim]
uri = '^https://dev.to/(.*)/(.*)/?'
uri_is_ambiguous = false

[proof]

[proof.request]
uri = "https://dev.to/api/articles/{{ claim_uri.parts.0 }}/{{ claim_uri.parts.1 }}"
protocol = "http"
access_restrictions = "none"

[proof.response]
format = "json"

[proof.target]
relation = "contains"
path = ["body_markdown"]