[about]
name = "Discourse"
shortname = "discourse"
homepage = "https://www.discourse.org"

[profile]
display = "{claim_uri_2}@{claim_uri_1}"
uri = "https://{claim_uri_1}/u/{claim_uri_2}"

[claim]
uri = '^https://(.*)/u/(.*)/?'
uri_is_ambiguous = true

[proof]

[proof.request]
uri = "https://{claim_uri_1}/u/{claim_uri_2}.json"
protocol = "http"
access_restrictions = "none"

[proof.response]
format = "json"

[proof.target]
format = "fingerprint"
relation = "contains"
path = ["user", "bio_raw"]