[about]
name = "Discourse"
shortname = "discourse"
homepage = "https://www.discourse.org"

[profile]
display = "{{ claim_uri.parts.1 }}@{{ claim_uri.parts.0 }}"
uri = "https://{{ claim_uri.parts.0 }}/u/{{ claim_uri.parts.1 }}"

[claim]
uri = '^https://(.*)/u/(.*)/?'
uri_is_ambiguous = true

[proof]

[proof.request]
uri = "https://{{ claim_uri.parts.0 }}/u/{{ claim_uri.parts.1 }}.json"
protocol = "http"
access_restrictions = "none"

[proof.response]
format = "json"

[proof.target]
relation = "contains"
path = ["user", "bio_raw"]