[about]
name = "DNS"
shortname = "dns"

[profile]
display = "{claim_uri_1}"
uri = "https://{claim_uri_1}"

[claim]
uri = '^dns:([a-zA-Z0-9.\-_]*)(?:\?(.*))?'
uri_is_ambiguous = false

[proof]

[proof.request]
uri = "{claim_uri}"
protocol = "dns"
access_restrictions = "server"

[proof.response]
format = "text"

[proof.target]
format = "uri"
relation = "contains"
path = []