[about]
name = "DNS"
shortname = "dns"

[profile]
display = "{{ claim_uri.parts.0 }}"
uri = "https://{{ claim_uri.parts.0 }}"

[claim]
uri = '^dns:([a-zA-Z0-9.\-_]*)(?:\?(.*))?'
uri_is_ambiguous = false

[proof]

[proof.request]
uri = "{{ claim_uri.full }}"
protocol = "dns"
access_restrictions = "server"

[proof.response]
format = "text"

[proof.target]
relation = "contains"
path = []