[about]
name = "Gitea"
shortname = "gitea"
homepage = "https://gitea.com"

[profile]
display = "{{ claim_uri.parts.1 }}@{{ claim_uri.parts.0 }}"
uri = "https://{{ claim_uri.parts.0 }}/{{ claim_uri.parts.1 }}"

[claim]
uri = '^https://(.*)/(.*)/gitea_proof/?'
uri_is_ambiguous = true

[proof]

[proof.request]
uri = "https://{{ claim_uri.parts.0 }}/api/v1/repos/{{ claim_uri.parts.1 }}/gitea_proof"
protocol = "http"
access_restrictions = "none"

[proof.response]
format = "json"

[proof.target]
relation = "contains"
path = ["description"]