[about]
name = "Gitea"
shortname = "gitea"
homepage = "https://gitea.com"

[profile]
display = "{claim_uri_2}@{claim_uri_1}"
uri = "https://{claim_uri_1}/{claim_uri_2}"

[claim]
uri = '^https://(.*)/(.*)/gitea_proof/?'
uri_is_ambiguous = true

[proof]

[proof.request]
uri = "https://{claim_uri_1}/api/v1/repos/{claim_uri_2}/gitea_proof"
protocol = "http"
access_restrictions = "none"

[proof.response]
format = "json"

[proof.target]
format = "uri"
relation = "contains"
path = ["description"]