[about]
name = "GitHub"
shortname = "github"
homepage = "https://github.com"

[profile]
display = "{{ claim_uri.parts.0 }}"
uri = "https://github.com/{{ claim_uri.parts.0 }}"

[claim]
uri = '^https://gist.github.com/(.*)/(.*)/?'
uri_is_ambiguous = false

[proof]

[proof.request]
uri = "https://api.github.com/gists/{{ claim_uri.parts.1 }}"
protocol = "http"
access_restrictions = "none"

[proof.response]
format = "json"

[proof.target]
relation = "contains"
path = ["files", "openpgp.md", "content"]