[about]
name = "Hacker News"
shortname = "hackernews"
homepage = "https://news.ycombinator.com"

[profile]
display = "{claim_uri_1}"
uri = "https://news.ycombinator.com/user?id={claim_uri_1}"

[claim]
uri = '^https://news.ycombinator.com/user\?id=(.*)/?'
uri_is_ambiguous = false

[proof]

[proof.request]
uri = "https://hacker-news.firebaseio.com/v0/user/{claim_uri_1}.json"
protocol = "http"
access_restrictions = "none"

[proof.response]
format = "json"

[proof.target]
format = "uri"
relation = "contains"
path = ["about"]