[about]
name = "Liberapay"
shortname = "liberapay"
homepage = "https://liberapay.com"

[profile]
display = "{{ claim_uri.parts.0 }}"
uri = "https://liberapay.com/{{ claim_uri.parts.0 }}"

[claim]
uri = '^https://liberapay.com/(.*)/?'
uri_is_ambiguous = false

[proof]

[proof.request]
uri = "https://liberapay.com/{{ claim_uri.parts.0 }}/public.json"
protocol = "http"
access_restrictions = "none"

[proof.response]
format = "json"

[proof.target]
relation = "contains"
path = ["statements", "content"]