[about]
name = "Lichess"
shortname = "lichess"
homepage = "https://lichess.org"

[profile]
display = "{{ claim_uri.parts.0 }}"
uri = "https://lichess.org/{{ claim_uri.parts.0 }}"

[claim]
uri = '^https://lichess.org/(.*)/?'
uri_is_ambiguous = false

[proof]

[proof.request]
uri = "https://lichess.org/api/user/{{ claim_uri.parts.0 }}"
protocol = "http"
access_restrictions = "none"

[proof.response]
format = "json"

[proof.target]
relation = "contains"
path = ["profile", "links"]