[about]
name = "Lobsters"
shortname = "lobsters"
homepage = "https://lobste.rs"

[profile]
display = "{{ claim_uri.parts.0 }}"
uri = "https://lobste.rs/u/{{ claim_uri.parts.0 }}"

[claim]
uri = '^https://lobste.rs/u/(.*)/?'
uri_is_ambiguous = false

[proof]

[proof.request]
uri = "https://lobste.rs/u/{{ claim_uri.parts.0 }}.json"
protocol = "http"
access_restrictions = "none"

[proof.response]
format = "json"

[proof.target]
relation = "contains"
path = ["about"]