[about]
name = "Mastodon"
shortname = "mastodon"
homepage = "https://joinmastodon.org"

[profile]
display = "@{{ claim_uri.parts.1 }}@{{ claim_uri.parts.0 }}"
uri = "https://{{ claim_uri.parts.0 }}/@{{ claim_uri.parts.1 }}"

[claim]
uri = '^https://(.*)/@(.*)/?'
uri_is_ambiguous = true

[proof]

[proof.request]
uri = "https://{{ claim_uri.parts.0 }}/@{{ claim_uri.parts.1 }}"
protocol = "http"
access_restrictions = "none"

[proof.response]
format = "json"

[proof.target]
relation = "contains"
path = ["attachment", "value"]