[about]
name = "Owncast"
shortname = "owncast"
homepage = "https://owncast.online"

[profile]
display = "{{ claim_uri.parts.0 }}"
uri = "https://{{ claim_uri.parts.0 }}"

[claim]
uri = '^https://(.*)/?'
uri_is_ambiguous = true

[proof]

[proof.request]
uri = "https://{{ claim_uri.parts.0 }}/api/config"
protocol = "http"
access_restrictions = "none"

[proof.response]
format = "json"

[proof.target]
relation = "contains"
path = ["socialHandles", "url"]