[about]
name = "Pleroma"
shortname = "pleroma"
homepage = "https://pleroma.social"

[profile]
display = "@{claim_uri_2}@{claim_uri_1}"
uri = "https://{claim_uri_1}/users/{claim_uri_2}"

[claim]
uri = '^https://(.*)/users/(.*)/?'
uri_is_ambiguous = true

[proof]

[proof.request]
uri = "https://{claim_uri_1}/users/{claim_uri_2}"
protocol = "http"
access_restrictions = "none"

[proof.response]
format = "json"

[proof.target]
format = "fingerprint"
relation = "contains"
path = ["summary"]