[about]
name = "Pleroma"
shortname = "pleroma"
homepage = "https://pleroma.social"

[profile]
display = "@{{ claim_uri.parts.1 }}@{{ claim_uri.parts.0 }}"
uri = "https://{{ claim_uri.parts.0 }}/users/{{ claim_uri.parts.1 }}"

[claim]
uri = '^https://(.*)/users/(.*)/?'
uri_is_ambiguous = true

[proof]

[proof.request]
uri = "https://{{ claim_uri.parts.0 }}/users/{{ claim_uri.parts.1 }}"
protocol = "http"
access_restrictions = "none"

[proof.response]
format = "json"

[proof.target]
relation = "contains"
path = ["summary"]