[about]
name = "Reddit"
shortname = "reddit"
homepage = "https://www.reddit.com"

[profile]
display = "{{ claim_uri.parts.0 }}"
uri = "https://www.reddit.com/user/{{ claim_uri.parts.0 }}"

[claim]
uri = '^https://(?:www.)?reddit.com/user/(.*)/comments/(.*)/(.*)/?'
uri_is_ambiguous = false

[proof]

[proof.request]
uri = "https://www.reddit.com/user/{{ claim_uri.parts.0 }}/comments/{{ claim_uri.parts.1 }}.json"
protocol = "http"
access_restrictions = "none"

[proof.response]
format = "json"

[proof.target]
relation = "contains"
path = ["data", "children", "data", "selftext"]