[about]
name = "Twitter"
shortname = "twitter"
homepage = "https://twitter.com"

[profile]
display = "@{{ claim_uri.parts.0 }}"
uri = "https://twitter.com/{{ claim_uri.parts.0 }}/status/{{ claim_uri.parts.1 }}"

[claim]
uri = '^https://twitter.com/(.*)/status/([0-9]*)(?:\?.*)?'
uri_is_ambiguous = false

[proof]

[proof.request]
uri = "https://publish.twitter.com/oembed?url={{ claim_uri.full | url_encode }}&omit_script=1"
protocol = "http"
access_restrictions = "none"

[proof.response]
format = "json"

[proof.target]
relation = "contains"
path = ['html']