name: build_target

on:  
  workflow_call:
    inputs:
      target: 
        type: string
        description: 'Build target'
        required: true
      channel: 
        type: string
        description: 'Build target'
        required: false
        default: 'stable'
      os: 
        type: string
        description: 'Operating system'
        required: false
        default: 'macos-latest'

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ${{inputs.os}}
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{inputs.channel}}
          target: ${{inputs.target}}
      
      - run: brew install nettle

      - run: cargo build --release --target ${{inputs.target}}
      
      - name: Test build
        run: |
          ./target/${{inputs.target}}/release/keyoxide --version

      - name: Package ${{inputs.channel}}-${{inputs.target}} release
        run: |
          tar -cvzf keyoxide-${{inputs.channel}}-${{inputs.target}}.tar.gz README.md LICENSE -C ./target/${{inputs.target}}/release keyoxide 

      - uses: actions/upload-artifact@v4
        with:
          name: keyoxide-${{inputs.channel}}-${{inputs.target}}
          path: keyoxide-${{inputs.channel}}-${{inputs.target}}.tar.gz