name: release
on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always
jobs:  
  build-linux-targets:
    name: Build targets
    uses: ./.github/workflows/_build_linux_target.yml
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu]
    with:
      target: ${{ matrix.target }}
      channel: stable

  build-macos-targets:
    name: Build targets
    uses: ./.github/workflows/_build_macos_target.yml
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-13
          - target: aarch64-apple-darwin
            os: macos-latest
    with:
      target: ${{ matrix.target }}
      channel: stable
      os: ${{ matrix.os }}
    
  create-release:
    needs: [build-linux-targets, build-macos-targets]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: keyoxide-*
          merge-multiple: true
          path:  ${{ github.workspace }}/builds/

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          draft: false
          files: |
            ${{ github.workspace }}/builds/*